version: "3.9"
services:
  postgres:
    container_name: localPostgresSQLDB2
    image: postgres
    environment:
      POSTGRES_DB: "local_db1"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5333:5432"
